### ISSUE TITLE
Create Login/Registration links in Navbar

### ISSUE THREAD

**Issue by NitinNair89** [NitinNair89/TheHungryRecipesApp#34]
**Is your feature request related to a problem? Please describe.**
Add links to login and registration pages in the navbar

**Comment by koshimagoyal** [comment]
Hi @NitinNair89 Assign it to me will work on this but according to current behaviour we can add only link for login because register page is used as child component in login page.

**Comment by NitinNair89** [comment]
Fixed by @koshimagoyal
