### ISSUE TITLE
Open the youtube link in a new tab

### ISSUE THREAD

**Issue by larissapissurno** [NitinNair89/TheHungryRecipesApp#44]
**Is your feature request related to a problem? Please describe.**
When I click on the 'Watch on YouTube' button, the current route is overrided by the youtube route.

**Describe the solution you'd like**
Open the youtube link in a new tab.

**Additional context**

![THR-issue-youtubelink](https://user-images.githubusercontent.com/8760873/139591495-6793b766-1852-46d8-a276-381e18f1ce0f.gif)

**Comment by larissapissurno** [comment]
@NitinNair89 hi, can you assign to me this one?

**Comment by NitinNair89** [comment]
> @NitinNair89 hi, can you assign to me this one?

Sure, please go ahead. 👍🏻

**Comment by NitinNair89** [comment]
@debobrototalukder

Please read the contributing guidelines. 🙂 

Before sending a PR, you have to claim an issue/ask for issue assignment to work upon. So unfortunately, I would have to reject your PR even though your PR is partially correct. It is missing some security issues with `target=_blank` attribute. We need to add a `rel` attribute to avoid a possible attack/stolen data/data misuse.

Please feel free to take up any other issues (by commenting first) and/or create new issues. You can also check the "Projects" tab to know the roadmap. 👍🏻

**Comment by debobrototalukder** [comment]
@NitinNair89 
Sorry for the misunderstanding & thank you for the explanation. I will go through them and follow the guidelines the next time. 

Thanks!

**Comment by NitinNair89** [comment]
> @NitinNair89 Sorry for the misunderstanding & thank you for the explanation. I will go through them and follow the guidelines the next time.
> 
> Thanks!

Sure, no problem. Please feel free to open/report bugs and also work on current issues/future issues (from Projects tab). Contributions are always welcome.
If anything interests you, please comment so I can assign it. 😃
